### PR TITLE
doctest: Fix regression after upgrade of reqwest to 0.10.

### PR DESCRIPTION
**Pull request by siedentop**
This was introduced in #350. Besides this, my thanks for upgrading
reqwest. The old version cost me some time yesterday.

I do not know why CI did not catch this. Maybe something for the maintainers to
take a look at. Or I made a mistake in my setup.

Below is the error I got:

```shell
---- /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/doc-comment-0.3.3/src/lib.rs - (line 228) stdout ----
error[E0433]: failed to resolve: use of undeclared type or module `reqwest`
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/doc-comment-0.3.3/src/lib.rs:245:27
   |
20 |     let client = reqwest::Client::new();
   |                           ^^^^^^ not found in `reqwest`
   |
help: consider importing this struct
   |
3  | use graphql_client::web::Client;
   |

error: aborting due to previous error
```

### CODE REVIEW

**Comment by siedentop** [comment]
CC: @boxdot , @tomhoule  (as you were both involved in #350).

**Comment by siedentop** [comment]
Might make sense to provide some CHANGELOG info, how to upgrade to the newest version. 

The diagnostics are pretty good (it says "use await") but it bears repeating.

Upgrading to the newest version of `graphql_client` requires that `send()` and `json()` become `send().await` and `json().await`.

```
error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> src/main.rs:101:23
    |
101 |           let mut res = client
    |  _______________________^
102 | |             .post("https://api.github.com/graphql")
103 | |             .bearer_auth(&github_api_token)
104 | |             .json(&q)
105 | |             .send()?;
    | |____________________^ the `?` operator cannot be applied to type `impl futures::Future`
    |
    = help: the trait `Try` is not implemented for `impl futures::Future`
    = note: required by `into_result`
help: consider using `.await` here
```

**Comment by siedentop** [comment]
Two more regressions

* Github example does not work anymore. This worked fine on macOS on tag v0.9.0, but not on latest master (9160417f9cdadf84e47bf0a0c888e9f1f9cd537a).
* My personal example fails with a tokio runtime panic. I'm trying to create a minimal example. And while tokio runtime issues are not the purview of this crate, the issue only appears after upgrading graphql-client.

```shell
❯ cargo run --example github graphql-rust/graphql-client

    Updating crates.io index
   Compiling pin-project-internal v1.0.2
   Compiling graphql-introspection-query v0.1.0 (/Users/user/src/tmp/graphql-client/graphql-introspection-query)
   Compiling graphql_client_codegen v0.9.0 (/Users/user/src/tmp/graphql-client/graphql_client_codegen)
   Compiling graphql_query_derive v0.9.0 (/Users/user/src/tmp/graphql-client/graphql_query_derive)
   Compiling pin-project v1.0.2
   Compiling futures-util v0.3.8
   Compiling graphql_client v0.9.0 (/Users/user/src/tmp/graphql-client/graphql_client)
   Compiling h2 v0.2.7
   Compiling hyper v0.13.9
   Compiling hyper-tls v0.4.3
   Compiling reqwest v0.10.8
   Compiling graphql_query_github_example v0.1.0 (/Users/user/src/tmp/graphql-client/examples/github)
    Finished dev [unoptimized + debuginfo] target(s) in 35.09s
     Running `target/debug/examples/github graphql-rust/graphql-client`
Error: error decoding response body: expected value at line 2 column 1

Caused by:
    expected value at line 2 column 1
```

**Comment by boxdot** [comment]
Thank you for investigating the regression!

> Reproducer is here: https://github.com/siedentop/graphql-reproducer

You have a mismatch of `reqwest` version 0.10.8 and `tokio` version 0.3. This version of `reqwest` still runs on tokio 0.2. Changing to tokio 0.2 fixed the panic.

I am still looking into the `expected value at line 2 column 1` problem.

**Comment by siedentop** [comment]
> Changing to tokio 0.2 fixed the panic.
Thank you! This is great.

> I am still looking into the expected value at line 2 column 1 problem.

I found it. It's newline characters in the serialization. 

Repro with curl: `curl -v -H "Authorization: bearer $GITHUB_API_TOKEN" -X POST -d @minimal.broken.json   https://api.github.com/graphql`

```
❯ cat minimal.broken.json
{
  "variables": { "owner": "siedentop", "name": "git-quickfix" },
  "query": "query {   viewer {\\n     login  }\\n}"
}
```

```
❯ cat minimal.json
{
  "variables": { "owner": "siedentop", "name": "git-quickfix" },
  "query": "query {viewer { login  }}"
}
```

**Comment by siedentop** [comment]
Found it. (For real this time ;) )

Put this in: `let body = res.bytes()?; debug!("Bytes: {:#?}", body);`

> Bytes: b"\r\nRequest forbidden by administrative rules. Please make sure your request has a User-Agent header (http://developer.github.com/v3/#user-agent-required). Check https://developer.github.com for other possible causes.\r\n"

**Comment by siedentop** [comment]
@tomhoule , IMO ready to merge.

@boxdot please review.

@tomhoule, one question: Would you be open to a second example very similar to this, that also used tokio to do multiple requests in parallel (while sharing the client connection)?

**Review by tomhoule — APPROVED** [review]
lgtm

**Comment by tomhoule** [comment]
@siedentop I would wait for https://github.com/graphql-rust/graphql-client/pull/338 before adding more examples with custom clients. Also I am a bit reluctant to add code when there is so little resources for maintenance. But I would definitely accept a good PR :)

**Review by boxdot — APPROVED** [review]

**Comment by boxdot** [comment]
Thank you for fixing the regression introduced by my MR.
